- geonode/geoserver/signals.py
Submitting this as a resolution to the issue described here: https://github.com/GeoNode/geonode/issues/2489
This will also enable custom layer/map thumbnail uploads in Boundless Exchange.
> Enable custom thumbnail persistence.

- geonode/templates/_permissions_form_js.html
This PR performs a refactor of how the upload permissions form is populated by applying the current user permissions for each permission form type by default. It was discovered that this is required in order to successfully configure GeoFence rules for the layer in Geoserver. Without this fix, it is possible for a user to upload a layer and not be able to view it on the layer details page, causing GeoNode permissions and GeoFence access rules to be out of sync.
> Apply default permission used in Geofence rule configuration.

- geonode/layers/admin.py
- geonode/layers/templates/layers/layer_detail.html
If style is missing, this line throws a index out of range error so we can safely escape it by checking if it is defined first.
> Avoid index out of range error when style is missing

- geonode/layers/views.py
- geonode/maps/views.py
- geonode/static/geonode/js/utils/thumbnail.js
1. views.py has been updated with two functionalities:
a. It now accepts the upload of a base64 encoded PNG as a thumbnail.
This is converted to a PNG in memory and saved.
b. It will return the URL of the thumbnail if there is one specified.
This was very handy for debugging the generation of thumbnails.
2. thumbnail.js now properly recognizes when there is a OL3-style
<canvas> and uses that to grab a thumbnail.  The OL3-style thumbnail
generation will parse the PNG data and send it to the server. The PNG
data is then handled appropriately by the changed described in part 1.
NODE-780
> Fix for thumbnail generation + ol3

- geonode/base/forms.py
Removed erroneous thumbnail url editing from the metadata
editing screen.
Like detail_url, thumbnail_url is really not intended to be editable.
> Remove thumbnail_url from the metadata editing.

- geonode/templates/search/_search_content.html
Added a new flag in the template that allows the 'Create a Map'
button to be shown even when layers are not the only facet being
displayed.
This is specifically useful for the new "Search" screen that can feature multiple facets.
> Added additional "include_create_map" flag.

- geonode/maps/views.py
When a missing layer is found during map_new the layer
_resolve_layer was not throwing a missing object exception but
was throwing Http404.  As Http404 was uncaught it was causing
the loop to fail instead of ignoring the missing data.
> Fix handling of missing layers.

- geonode/layers/views.py
GeoNode was filtering non-WMS layers out from the layer/source
definition when passing it into the layer view.  This version passes on
all layer information and leaves it to the clients to filter.
NODE-840
> Allow all layers to be passed to mapviewer.

- geonode/static/geonode/js/search/search.js
Added a MaxBounds to the leaflet map. This prevents the user from making invalid extent filters.
Refs: NODE-389
> Fix for "overrunning" the extent filter map.

- geonode/static/geonode/js/search/search.js
The extent was not clearing when the extent filter was closed.
This updates the code to remove 'extent' from the query when the panel is shut.
> Fix sticky extent filter in searches

- geonode/geoserver/helpers.py
- geonode/security/models.py
- Removes duplicate ```set_default_permissions``` from update layers. Geonode will already set the default permissions on layer creation.
- Geofence will now not create rules for Anonymous user/group. This was not providing any access control. Instead, when anonymous view/download are enabled, geonode is creating a rule in geofence making the layer public. This hasn't changed, and unauthenticated WFS-T requests are still possible.
- Owner of a layer now always gets full access on a layer in geofence.
- Workspace in Geofence rules is now retrieved from layer, instead of being hard coded.
> Updatelayers and Geofence permissions

- geonode/version.py
This adds the short form github commit to the version string (NODE-623).
```
from pip._vendor import pkg_resources
[p.version for p in pkg_resources.working_set if p.project_name == 'GeoNode']
```
```['2.6a1.806b041']```
> Add github commit to version

- geonode/geoserver/helpers.py
Currently adding layers from a WMS store may fail.
This skips attempting setting a null style, which will allow WMS layers to be added to geonode.
> Skip default style when doesn't exist 

- geonode/people/forms.py
This removes the clean_username method.
When adding an account with an existing username this method will raise a 500, instead of just warning the user the account/username already exist.
Users will now see the error specified din the migration:
https://github.com/boundlessgeo/geonode/blob/exchange/1.2.0/geonode/people/migrations/24_initial.py#L26
> Remove clean_username

- setup.py
Pinning geonode-user-account to 1.0.13 - 1.0.15 migrations currently break Exchange build. Credit to Ami for discovering this.
> pinning geonode-user-account

- geonode/layers/views.py
Added a default value for the "TIME" parameter for image downloads so that all features will be retrieved.
Fixes [BEX-225](https://issues.boundlessgeo.com:8443/browse/BEX-225)
Steps:
1. Upload a time-enabled layer, such as `american_civil_war_227b6a2b_abfc8178`, and enable time support.
2. In Exchange, navigate to `Data > Layers > [uploaded_layer]`.
3. Click `Download Layer`.
4. Click an image link in the `Images` tab.
> Fixed image downloads for time-enabled layers

- geonode/services/templates/services/service_register.html
Update error message to spell out spaces and better specify allowed characters
> Service name must start with a letter, followed by letters, numbers, or the . - _ (period, dash, underscore) characters. No spaces allowed.
> Better service registration error message

- geonode/templates/search/_search_content.html
Previously the "Set permissions" and "Create a
Map" buttons were designed in such a way that the
text would overflow the buttons and collide with
each other at certain page widths. This behavior
isn't desired, and the buttons were redesigned to
have a clean look and feel regardless of the page
width.
Relates to Exchange PR: https://github.com/boundlessgeo/exchange/pull/447
> Update workspace buttons layout and text

- geonode/admin.py
- geonode/urls.py
Without this change, the django admin page will not list any modules/apps.
> assign custom AdminSite for app discovery.

- geonode/services/management/commands/importservice.py
While the `importservice` command worked to register the service, I was getting some errors in the response output.  The `response` didn't seem to have a `content` attribute and the `id` from `json.loads(response)[0]` was named `service_id`
> importservice response and service_id

- geonode/services/forms.py
- geonode/services/serviceprocessors/base.py
- geonode/services/serviceprocessors/mapserver.py
- geonode/services/serviceprocessors/wms.py
MapLoom  assumes Tilemap is supported for ESRI REST services so we check the service for Tilemap support and prevent registration/import if its not available.
Service with Tilemap support:
http://services.arcgisonline.com/arcgis/rest/services/Demographics/USA_Median_Age/MapServer/
Service without TIlemap support:
https://maps.cityofmadison.com/arcgis/rest/services/Parking/OnStreetRestrictions/MapServer/
Error message:
> Check for basic capabilities

- geonode/layers/views.py
Without this change, there is the potential for a MultipleObjectsReturned exception to be returned. Since we were already verifying that the service exists given the typename prefix, it makes sense to use the service id in the layer query so as to avoid the MultipleObjectsReturned exception.
> Make the lookup more specific.

- geonode/services/forms.py
Based on updated requirements we no longer prevent registration based on unsupported capabilities
> Remove the capabilities pre-check

- geonode/layers/models.py
This resolves the issue where the search results provide the incorrect typename if the layer is remote.
> Use service_typename as it covers both local and remote

- geonode/layers/views.py
1. Added ptype to allow the detail to delineate between
ESRI and WMS type services.
2. Changed URL to switch between the server URL and the tiled URL
based on whether the layer is local or remote.
refs: BEX-654
> Add ptype and fix url for remote servers

- geonode/services/templates/services/service_list.html
Long URLs were causing the table to get wider than
the available display. This truncates the URL length
to something more reasonable.
refs: BEX-697
> Prevent the table from overflowing.

- geonode/base/admin.py
This PR hides action(s) in django admin if the user doesn't have permission to invoke them.
> suppress actions if not authorized

- geonode/people/models.py
- requirements.txt
- setup.py
This PR makes sure that Exchange is handling bringing in geonode-elasticsearch app and removes the indexing function from the geonode model in order to further separate the functionality provided by this app.
Goes along with https://github.com/boundlessgeo/geonode-elasticsearch/pull/63
Also requires forthcoming PR to Exchange.
> remove indexing from profile

- geonode/security/middleware.py
Returns the path, plus an appended query string, if applicable.
ISSUE:
If I am following a link to an Exchange installation that was sent to me by a colleague and I am redirected to the login screen when I click that link, the base link is the only portion of the original link preserved, so I lose the context of the shared link when I'm redirected after a successful login.
So:
https://exchange-dev.boundlessgeo.io/maps/new?layer=fibercable_377dcbaa
Becomes:
https://exchange-dev.boundlessgeo.io/maps/new
...after login.
> Use request.get_full_path()

- geonode/layers/views.py
Need an easy way for the caller of this method to determine whether the user has edit permissions to the layers style.
> Include perms dict in layer metadata response

- geonode/security/middleware.py
Returns the path, plus an appended query string, if applicable.
Backport from 1.5.x, to facilitate PKI work.
> Backport: Use request.get_full_path() (#160)

- geonode/base/admin.py
- geonode/layers/admin.py
This PR updates the django admin for layers to allow the admin user to filter layers by whether a default style has been set. The PR also enables a new Layers admin action to synchronize the registered styles with the active style records in Geoserver. Lastly, this PR enables object permissions to be managed via the django admin 'object permissions' button.
> Adds default style filter, remote sync action, and perms management

- geonode/utils.py
Assuming index 0 will always be the local geoserver is prone to many configuration errors. Therefore we remove that condition and defer to the config process on line 384. This fix also prevents duplication of the local geoserver url source, resulting in redundant getCaps calls in the mapping client.
> Fix base layer config

- geonode/utils.py
Assuming index 0 will always be the local geoserver is prone to many configuration errors. Therefore we remove that condition and defer to the config process on line 384. This fix also prevents duplication of the local geoserver url source.
> Fix base layer config (#186)

- geonode/utils.py
This PR sets the geoserver source for the default config only so that Maploom is able to preload the source although there are no layers included. When the layers= param is included for /maps/new, the local source is automatically added via the source layer.
Test Steps:
1. go to /maps/new
2. launch the layer add modal
3. Add a layer to the map
If this change is not applied, step 3 would fail.
> Add default geoserver source

- geonode/services/forms.py
- geonode/services/templates/services/service_edit.html
- geonode/services/views.py
It was determined that it is important to be able
to specify which caveats should be applied to which
classification. This change tweaks the CLASSIFICATION_LEVELS
setting, and makes use of the new format to ensure
only the caveats that apply to a particular classification
are able to be selected.
> Reconfigure use of CLASSIFICATION_LEVELS

- geonode/base/models.py
This change will allow GeoServer to use the auth token from the external auth provider.
> Don't create a new token if we already have one.

- geonode/security/middleware.py
With this setting enabled, Exchange will bypass the local login page and force redirect to the user to login via the external provider.
> Allow the app to skip the local login page and force redirect to the external auth provider.

- geonode/contrib/createlayer/utils.py
- geonode/layers/urls.py
- geonode/layers/views.py
Since Exchange uploads remove the `geonode:` from the type name, lets follow the same approach for create layer. Also there's no need to set the bbox info because it get overridden by the Geoserver response.
This PR also addresses the following BEX-987 items:
1. Extent issue when the layer is reloaded in Maploom when a feature has been added. The map does not zoom to the correct location of the feature
2. Missing basemap and map preview under layer details page
Error Test Steps:
Points, Lines and Polygons
STEPS:
- Data, Create Layer
- Create point, line or polygon layer
- Add attribute
- Create
- In maploom, Add a feature
- Show style editor
- Make changes to the style and Save
- Error
- For the same created layer, add a feature. *Note:* Requires an update to MapLoom which will call …
> Update layer args

- geonode/base/models.py
BEX-971
Sometimes the Remote Thumbnail url is missing the list of layers so lets check and return the missing thumbnail image rather than a broken url.
The users activity feed under Profile contains broken images for maps with remote service layers.
> Check for layers in reflected url

- geonode/layers/views.py
User is seeing remote service layers showing up disabled when a map is saved with only remote services and then reloaded from Explore Maps. The user is able to successfully add the remote service layers and save the map but when the map is reloaded from Explore Maps, the layers show up disabled.
This issue is occurring when the Add Layer dialog in Maploom is used
STEPS:
- Create map
- Add Remote Services from Add Layer Dialog
- Save map
- Maps, Explore Maps
- Click on the saved map to open
- Layers show up disabled
> Slugify the name for consistency

- geonode/layers/views.py
Seeing a few issues with removing layers
- Removing a layer is causing the thumbnails to turn white when the user is returned to the search page
- User is unable to click on the thumbnail to create a map
- All other layers will not load in Maploom when the user clicks on the name of the layer to create a map
- Deleted layer remains in search, clicking on the name or view details causes a page error
- *All reported issues resolve if the user refreshes the browser or navigates to another page*
STEPS:
- Data, Layers
- View Details
- Edit Layer
- Remove Layer
- Yes
> Redirect to search instead

- geonode/services/serviceprocessors/wms.py
This service failed to register because it only has one advertised layer. This PR prevents the one layer exclusion and checks for > 0.
https://basemap.nationalmap.gov/arcgis/services/USGSImageryTopo/MapServer/WMSServer?request=GetCapabilities&service=WMS
> One layer minimum

- geonode/security/models.py
The change permissions for documents and maps is not saving when unchecking Anyone and applying the changes.
A map or document that has its permissions changed to just admin is still available for the test user when they log on. The test user can view the document and is able to open the map but the layer is disabled in Maploom.
STEPS:
- Login with Admin
- Upload a document
- Change document permissions
- Remove Anyone and Apply Changes for just admin
- Login with Test
- Document is available 
or
- Login with Admin
- Select and create a map with a layer
- Save Map
- Maps, Explore Maps, View Details
- Change Map Permisisons
- Remove Anyone and Apply changes
> Clear perms for non-layers

- geonode/layers/views.py
- geonode/services/forms.py
- geonode/services/serviceprocessors/mapserver.py
- geonode/utils.py
- setup.py
New PR for https://github.com/boundlessgeo/geonode/pull/249
Since we do not want to put changes in GeoNode, the old code changes are going to be extracted into the Exchange PR and a custom app. These changes are all that will be relevant for GeoNode now.
**layers/views.py**
bug fix for using correct proj in JS clients
**services/serviceprocessors/mapserver.py**
bug fix for empty layers list in list of parsed_service layers
**utils.py**
bug fix for incorrect syntax on raised exception
**setup.py**
removal of ArcREST installation from GeoNode so that our custom ArcREST package will be installed (this is actually the only portion relevant to getting PKI working)
**services/forms.py**
refactors how we use the `CLASSIFICATION_LEVELS` and `CAVEATS` variables in accordance with adjustments to …
> GeoNode bug fixes and PKI preparation

- geonode/services/templates/services/service_resources_harvest.html
On systems with poor network responsiveness
the low refresh time causes the harvest page
to become unusable in the event that a resource
fails to be harvested. This new timeout should
strike a balance between refreshing the page
frequently enough to update the status of "IN
PROGRESS" items without breaking things in the
event of a failure.
> Increase page refresh timer on harvest

- geonode/maps/views.py
Cast `bbox` to a list, as it can otherwise end up here as a `tuple` object, which will cause failures when loading in MapLoom. This error seems to occur only when:
- The Layers are harvested from a WMS Service
- Multiple of said Layers are selected in the workspace and opened in map viewer
> Cast bbox to list to prevent tuple error

- geonode/layers/views.py
- geonode/maps/views.py
- geonode/utils.py
Fixes the geonode-client's bbox to take into account the settings for our target srid.
Also corrects the ordering of the bbox in `bbox_to_projection` to match what is returned by the model.
Coincides with: https://github.com/boundlessgeo/exchange/pull/62
> Fixing incorrect loading of bbox for remote services

- geonode/layers/templates/layers/layer_replace.html
- geonode/layers/templates/upload/layer_upload_base.html
Previously the button pointed to the explore layers
section. This makes sense when you are trying to
upload a layer in general, (which is the template
the layer replace page inherits from) however when
you're replacing a specific layer, it makes more
sense to return to that specific layer as your
"go back" action.
> Fix Return to Layers button on replace page
