boundlessgeo/geonode

geonode/layers/search_indexes.py

used to enable using unified search for maploom search results

add geogig_link to elastic search results

---

geonode/layers/views.py

fixes a bug whereas category changes in metadata editing were not being saved, addresses part of node 780

fix bug with category saving

---

geonode/static/geonode/js/upload/LayerInfo.js
geonode/static/geonode/js/upload/upload.js

Addresses [NODE-801](https://issues.boundlessgeo.com:8443/browse/NODE-801)

Correctly handle file names with spaces or parentheses

---

geonode/static/geonode/js/upload/LayerInfo.js

Addresses [NODE-813](https://issues.boundlessgeo.com:8443/browse/NODE-813)

Fixed incorrect DOM name to create geogig store

---

geonode/upload/files.py

Addresses [NODE-802](https://issues.boundlessgeo.com:8443/browse/NODE-802)

Handle OS X zipped files in upload

---

geonode/layers/search_indexes.py

This PR adds the fields required for storyscapes search.

Includes additional fields in the search index

---

geonode/layers/views.py

Add layer attributes to the json response

---

geonode/geoserver/helpers.py
geonode/geoserver/signals.py

This will add/remove layergroups using updatelayers. Only layergroups within a workspace will be processed.
@davisc

Layergroup support in updatelayers

---

geonode/layers/search_indexes.py
geonode/static/geonode/js/search/search.js
geonode/templates/search/_general_filters.html

`has_time` is a Boolean field representing whether or not
a layer has been configured with time.

Added new facet and UI for time.

---

geonode/templates/search/_sort_filters.html

Addressing [NODE-718](https://issues.boundlessgeo.com:8443/browse/NODE-718)

Fix to correctly show icons on people and group filters

---

geonode/upload/utils.py

This allows geogig to be initialized in a schema other than the public schema

Geogig postgres schema

---

geonode/templates/metadata_form_js.html

Coincides with: https://github.com/boundlessgeo/exchange/pull/333

Adjust promise resolution with angular bump to 1.6.5

---

geonode/settings.py

Add celery queues so layers delete

---

geonode/urls.py
geonode/views.py

Clear cart cookies on logout

---

geonode/services/forms.py

Remember to add the facets config as described in the following PR if enabled.
https://github.com/boundlessgeo/exchange/pull/408

Only show fields when classification is enabled

---

geonode/security/models.py

This change configures the rules as seen in the image below... If anonymous, give all users read-only access.. notice WFS Transaction is not explicitly given to non authorized users.

remove boilerplate public access and set user * if anonymous

---

geonode/base/forms.py
geonode/settings.py

Adds the ability to configure a list of words that will be removed from keywords.

add ability to filter out keywords

---

geonode/documents/models.py
geonode/groups/models.py
geonode/layers/models.py
geonode/maps/models.py
geonode/people/models.py
geonode/settings.py
requirements.txt

Geonode code update end of this update: https://github.com/boundlessgeo/exchange/pull/468

Updating models with indexing functions for elasticsearch app

---

geonode/settings.py
requirements.txt

Adjusting repo and name of app

Fixing bug with elasticsearch app

---

setup.py

Can only be merged when https://github.com/boundlessgeo/exchange/pull/509 is merged

Elasticsearch 6 dependency 

---

geonode/documents/models.py

This will allow the bbox to be altered by the user.

Set defaults only if bbox is None

---

geonode/services/templates/services/service_detail.html

Refresh the page so the user doesn't think the page is stuck on QUEUED or INPROCESS

refresh page on a 7 second interval

---

geonode/documents/templates/documents/document_upload.html

Perform case insensitive lookup.

Case insensitive search

---

geonode/security/models.py

This removes the username from the payload if username is `anonymoususer`

geofence public access fix

---

geonode/services/templates/services/service_detail.html

Reverts boundlessgeo/geonode#144

Revert "Enable using online_resource for HTTPS remote services"

---

geonode/services/serviceprocessors/handler.py
geonode/services/serviceprocessors/mapserver.py
geonode/services/serviceprocessors/wms.py
geonode/services/tasks.py
geonode/services/views.py
geonode/utils.py

Reverts boundlessgeo/geonode#143

Revert "Update remote services to handle headers, for passing access token"

---

geonode/layers/views.py

Added fields missing from the previous JSON view of the layer.
Including:
- Attribute statistics
- Temporal extent start/end
- Linked Maps
Same as #149 but based on 1.5.x

Added addtional fields to the layer REST API

---

geonode/layers/forms.py

Exclude field alternate from the edit form.

Alternate should be immutable like typename

---

geonode/geoserver/helpers.py
geonode/geoserver/views.py

Account for GET requests also.

Bex 823 backport

---

geonode/geoserver/views.py

To allow maploom and other clients to edit styles.

add csrf_exempt

---

geonode/layers/views.py

Address PSBEX-93 by properly passing query parameters in `params` field rather than directly in url

Add query params to source_params and remove them from the url

---

geonode/layers/views.py

Need an easy way for the caller of this method to determine whether the user has edit permissions to the layers style.

Include style edit perms

---

geonode/base/forms.py
geonode/layers/views.py

Bex704 Make Category not required

---

geonode/layers/views.py
geonode/maps/views.py
geonode/services/serviceprocessors/handler.py
geonode/services/serviceprocessors/mapserver.py
geonode/services/serviceprocessors/wms.py

Update remote services thumbnail creation for pki

---

geonode/utils.py

This needs to be updated from `requires_ssl_proxy` to `uses_proxy_route` as per my discussion with @dakcarto .
In addition, I have been unable to test this with a remote basemap due to 500 errors.

Have basemap prefer ssl config settings to determine proxy

---

geonode/geoserver/views.py

httplib caused issues on staging so requests is preferred.

Use requests vs httplib

---

geonode/base/admin.py
geonode/layers/admin.py

* Adds default style filter and remote sync action
* Adds GuardedModelAdmin

Adds default style filter, remote sync action, and perms management

---

geonode/layers/admin.py
geonode/layers/views.py

Provides user feedback as to what and how many items were successful. Also include the workspace in the response to /get

Update admin action to provide user feedback

---

geonode/utils.py

See: https://github.com/boundlessgeo/exchange/pull/639

Backport sources fix to 1.4.x

---

geonode/layers/models.py

Adds service fields to the layer elastic index.

add CMP5 fields to elastic index

---

geonode/services/forms.py

Just looking for confirmation from @dakcarto that this satisfies what we spoke about for [PSBEX-65].

Add validation to service registration and inform user of any errors

---

geonode/groups/templates/groups/group_list.html
geonode/people/templates/people/profile_list.html
geonode/services/serviceprocessors/mapserver.py
geonode/settings.py
requirements.txt
setup.py

Backports the work done in 1.5 to move search into a separate app. Also fixes search for users and groups.

Backport movedsearch

---

setup.py

this is brought in by the geonode-elasticsearch app

remove elasticsearch_dsl

---

geonode/social/views.py

Adds filter so that a user can only view actions related to items they have permission to view.

Filter actions

---

geonode/base/models.py
geonode/layers/views.py
geonode/maps/views.py
geonode/services/serviceprocessors/mapserver.py
geonode/social/templates/social/_activity_item.html
geonode/utils.py

This reverts commit 5a9a55ce49b8916509c9afcd15010726e420cd00, reversing
changes made to 6872ba3c9caa858a9b2c29e37f7cd4159131d481.
These changes require GDAL updates we do not currently have.

Revert "Merge pull request #246 from boundlessgeo/merge-wkt_srs"

---

geonode/base/models.py
geonode/layers/views.py
geonode/maps/views.py
geonode/services/serviceprocessors/mapserver.py
geonode/social/templates/social/_activity_item.html
geonode/utils.py

Adds `1.4.12.2` commits, sans the commit from bitner for wkt parsing fix, which requires gdal updates. Aligns us with `1.4.x` and ready to merge. The wkt fix should be cherry-picked on top/reverted again when we are ready to update gdal in our docker environment/deployments.

Ps/pki 1.4.12.2

---

geonode/layers/models.py
geonode/services/models.py
geonode/services/serviceprocessors/mapserver.py

NOTE: will break your dev box's ability to harvest resources if you do not have a **machine installed** GDAL>=2.3.1

Wkt revert revert
